version: "3.9"
services:
  db:
    image: postgres:16
    container_name: hs_db
    environment:
      POSTGRES_DB: homeservice
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
